### ISSUE TITLE
Difference data structure with dosbox on level 1 start

### ISSUE THREAD

**Issue by turican0** [GrimSqueaker/remc2#26]
D41A0_BYTESTR_0+0x8fb0 X 0x356038+0x8fb0 -fixed
D41A0_BYTESTR_0+0x8fb0 X 0x356038+0xd49a -work on it

**Comment by turican0** [comment]
D41A0_BYTESTR_0+0x8fb0 X 0x356038+0xd49a -fixed
next differences is in 3. frame
(0x356038+57 fixed(bad sign of variable), next difference is on 0x356038+79)

**Comment by turican0** [comment]
Fixed first 216 frames in level 1, meybe ok. Some errors maybe fixed. I test it tomorrow!

**Comment by turican0** [comment]
Size of SLEV1.dat is now shorter. 224790 versus 224791(good size), I find difference.

**Comment by GrimSqueaker** [comment]
Sorry, I think I broke this when I used sizeof(...) for saving games. The question would also be: Do we want 100% compatibility to save games of the original? I think for the moment at least that would be good - not just for debugging.
But the problem was that the save game function was taking the first byte after the struct that is saved to the file. So either in the original that last byte was just not used/noticed or something is wrong in the struct itself.
An easy fix would also be to just add one padding byte at the end of the struct - if all the location of data is correct otherwise.

**Comment by turican0** [comment]
I fixed it(add stub byte to structure). The error was there before (wrong structure size), with sizeof save only manifested.
Binary compactibility with original is good. Any player can send savefile to other player regardless of whether it will have the original or remc2 32-bit or remc2 64bit. If possible I would try to complactibility to keep it.

**Comment by GrimSqueaker** [comment]
Yes, and if the data in the future changes, then we can also write an import that detects saves of the original version. The other way around, however, might be impossible.

**Comment by turican0** [comment]
I think if we store the same information, we will be able to import and export for savefile and maintain compatibility. If we store more information, we can add another file. Pointers are recalculated after uploading, so there should be no problem with them. In the meantime, Compatibility is also essential for debugging errors. I would try to maintain compatibility when the problem arises, we will definitely come up with a solution.
Tom.
